#!/usr/bin/env node

"use strict"

const fs = require("fs")
const path = require("path")

const projectRoot = path.resolve(__dirname, "..")
const defaultReferenceCsv = path.resolve(
  projectRoot,
  "../桌面/openvela_ui/smart-band-ui-redesign/data/administrative-divisions-level3.csv"
)
const inputPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : defaultReferenceCsv
const outputPath = process.argv[3]
  ? path.resolve(process.argv[3])
  : path.join(
      projectRoot,
      "packages/demos/openvela_ui/openvela_ui_city_data.c"
    )

const qweatherLocationIds = {
  "1101": "101010100",
  "3101": "101020100",
  "3201": "101190101",
  "3202": "101190201",
  "3205": "101190401",
  "3301": "101210101",
  "3302": "101210401",
  "3501": "101230101",
  "3502": "101230201",
  "3701": "101120101",
  "3702": "101120201",
  "4101": "101180101",
  "4201": "101200101",
  "4205": "101200901",
  "4301": "101250101",
  "4401": "101280101",
  "4403": "101280601",
  "4406": "101280800",
  "5101": "101270101",
  "5107": "101270401"
}

function parseCsvLine(line) {
  const match = line.match(
    /^(\d+),(\d+),(\d+),"([^"]*)","([^"]*)","([^"]*)","([^"]*)","([^"]*)"$/
  )
  if (!match) throw new Error("Unsupported CSV row: " + line)
  return {
    id: match[1],
    pid: match[2],
    depth: Number(match[3]),
    shortName: match[4],
    administrativeCode: match[7].slice(0, 6),
    name: match[8]
  }
}

function readRows() {
  const source = fs.readFileSync(inputPath, "utf8")
    .replace(/^\uFEFF/, "")
    .trim()
  const lines = source.split(/\r?\n/)
  if (lines.length < 2 || lines[0].indexOf("id,pid,deep") !== 0) {
    throw new Error("Unexpected administrative division CSV header")
  }
  return lines.slice(1).map(parseCsvLine)
}

function buildData(rows) {
  const provinceRows = rows.filter(function (row) {
    return row.depth === 0 && row.shortName !== "国外"
  })
  const cityRows = rows.filter(function (row) { return row.depth === 1 })
  const districtRows = rows.filter(function (row) { return row.depth === 2 })
  const citiesByProvince = Object.create(null)
  const districtsByCity = Object.create(null)

  cityRows.forEach(function (city) {
    if (!citiesByProvince[city.pid]) citiesByProvince[city.pid] = []
    citiesByProvince[city.pid].push(city)
  })
  districtRows.forEach(function (district) {
    if (!districtsByCity[district.pid]) districtsByCity[district.pid] = []
    districtsByCity[district.pid].push(district)
  })

  const provinces = []
  const cities = []
  const districts = []
  provinceRows.forEach(function (province) {
    const provinceCities = citiesByProvince[province.id] || []
    const firstCity = cities.length
    provinceCities.forEach(function (city) {
      const cityDistricts = districtsByCity[city.id] || []
      const firstDistrict = districts.length
      cityDistricts.forEach(function (district) {
        districts.push(district.name)
      })
      cities.push({
        name: city.name,
        shortName: city.shortName,
        locationId: qweatherLocationIds[city.id] || "",
        firstDistrict: firstDistrict,
        districtCount: cityDistricts.length
      })
    })
    provinces.push({
      name: province.name,
      firstCity: firstCity,
      cityCount: provinceCities.length
    })
  })
  return { provinces: provinces, cities: cities, districts: districts }
}

function cString(value) {
  return JSON.stringify(String(value))
}

function assertGeneratedData(data) {
  /* The upstream CSV also contains a synthetic province/city/district chain
   * named "国外".  It is not a Chinese administrative division and the
   * reference Quick App deliberately excludes that entire chain. */
  if (data.provinces.length !== 34 ||
      data.cities.length !== 392 ||
      data.districts.length !== 3209) {
    throw new Error(
      "Administrative data count mismatch: " +
      data.provinces.length + " provinces, " +
      data.cities.length + " cities, " +
      data.districts.length + " districts"
    )
  }
  if (data.cities.length > 65535 || data.districts.length > 65535) {
    throw new Error("Generated indexes exceed uint16_t capacity")
  }
}

function render(data) {
  const lines = []
  lines.push("/* Auto-generated by tools/generate_city_data.js; do not edit. */")
  lines.push("/* Source: AreaCity-JsSpider-StatsGov level-3 data, version")
  lines.push(" * 2025.251231.260403 (2026-04-03).  The synthetic `国外` chain")
  lines.push(" * is excluded, leaving 34 provinces, 392 cities and 3209 districts. */")
  lines.push("")
  lines.push("#include \"openvela_ui_city_data.h\"")
  lines.push("")
  lines.push("#include <stdint.h>")
  lines.push("")
  lines.push("struct city_province_data_s {")
  lines.push("    const char *name;")
  lines.push("    uint16_t first_city;")
  lines.push("    uint16_t city_count;")
  lines.push("};")
  lines.push("")
  lines.push("struct city_city_data_s {")
  lines.push("    const char *name;")
  lines.push("    const char *short_name;")
  lines.push("    const char *location_id;")
  lines.push("    uint16_t first_district;")
  lines.push("    uint16_t district_count;")
  lines.push("};")
  lines.push("")
  lines.push("static const char g_empty_string[] = \"\";")
  lines.push("")
  lines.push("static const struct city_province_data_s g_provinces[] = {")
  data.provinces.forEach(function (province) {
    lines.push(
      "    {" + cString(province.name) + ", " +
      province.firstCity + ", " + province.cityCount + "},"
    )
  })
  lines.push("};")
  lines.push("")
  lines.push("static const struct city_city_data_s g_cities[] = {")
  data.cities.forEach(function (city) {
    lines.push(
      "    {" + cString(city.name) + ", " + cString(city.shortName) + ", " +
      cString(city.locationId) + ", " + city.firstDistrict + ", " +
      city.districtCount + "},"
    )
  })
  lines.push("};")
  lines.push("")
  lines.push("static const char *const g_districts[] = {")
  data.districts.forEach(function (district) {
    lines.push("    " + cString(district) + ",")
  })
  lines.push("};")
  lines.push("")
  lines.push("#define ARRAY_COUNT(array) (sizeof(array) / sizeof((array)[0]))")
  lines.push("")
  lines.push("static const struct city_city_data_s *city_data(")
  lines.push("    size_t province_index, size_t city_index)")
  lines.push("{")
  lines.push("    const struct city_province_data_s *province;")
  lines.push("")
  lines.push("    if (province_index >= ARRAY_COUNT(g_provinces)) {")
  lines.push("        return NULL;")
  lines.push("    }")
  lines.push("")
  lines.push("    province = &g_provinces[province_index];")
  lines.push("    if (city_index >= province->city_count) {")
  lines.push("        return NULL;")
  lines.push("    }")
  lines.push("")
  lines.push("    return &g_cities[province->first_city + city_index];")
  lines.push("}")
  lines.push("")
  lines.push("size_t openvela_ui_city_province_count(void)")
  lines.push("{")
  lines.push("    return ARRAY_COUNT(g_provinces);")
  lines.push("}")
  lines.push("")
  lines.push("const char *openvela_ui_city_province_name(size_t province_index)")
  lines.push("{")
  lines.push("    if (province_index >= ARRAY_COUNT(g_provinces)) {")
  lines.push("        return g_empty_string;")
  lines.push("    }")
  lines.push("")
  lines.push("    return g_provinces[province_index].name;")
  lines.push("}")
  lines.push("")
  lines.push("size_t openvela_ui_city_city_count(size_t province_index)")
  lines.push("{")
  lines.push("    if (province_index >= ARRAY_COUNT(g_provinces)) {")
  lines.push("        return 0;")
  lines.push("    }")
  lines.push("")
  lines.push("    return g_provinces[province_index].city_count;")
  lines.push("}")
  lines.push("")
  lines.push("const char *openvela_ui_city_city_name(size_t province_index,")
  lines.push("                                       size_t city_index)")
  lines.push("{")
  lines.push("    const struct city_city_data_s *city =")
  lines.push("        city_data(province_index, city_index);")
  lines.push("")
  lines.push("    return city ? city->name : g_empty_string;")
  lines.push("}")
  lines.push("")
  lines.push("const char *openvela_ui_city_city_short_name(size_t province_index,")
  lines.push("                                             size_t city_index)")
  lines.push("{")
  lines.push("    const struct city_city_data_s *city =")
  lines.push("        city_data(province_index, city_index);")
  lines.push("")
  lines.push("    return city ? city->short_name : g_empty_string;")
  lines.push("}")
  lines.push("")
  lines.push("const char *openvela_ui_city_city_location_id(size_t province_index,")
  lines.push("                                              size_t city_index)")
  lines.push("{")
  lines.push("    const struct city_city_data_s *city =")
  lines.push("        city_data(province_index, city_index);")
  lines.push("")
  lines.push("    return city ? city->location_id : g_empty_string;")
  lines.push("}")
  lines.push("")
  lines.push("size_t openvela_ui_city_district_count(size_t province_index,")
  lines.push("                                       size_t city_index)")
  lines.push("{")
  lines.push("    const struct city_city_data_s *city =")
  lines.push("        city_data(province_index, city_index);")
  lines.push("")
  lines.push("    return city ? city->district_count : 0;")
  lines.push("}")
  lines.push("")
  lines.push("const char *openvela_ui_city_district_name(size_t province_index,")
  lines.push("                                           size_t city_index,")
  lines.push("                                           size_t district_index)")
  lines.push("{")
  lines.push("    const struct city_city_data_s *city =")
  lines.push("        city_data(province_index, city_index);")
  lines.push("")
  lines.push("    if (!city || district_index >= city->district_count) {")
  lines.push("        return g_empty_string;")
  lines.push("    }")
  lines.push("")
  lines.push("    return g_districts[city->first_district + district_index];")
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

const data = buildData(readRows())
assertGeneratedData(data)
fs.writeFileSync(outputPath, render(data), "utf8")
process.stdout.write(
  "Generated " + outputPath + ": " +
  data.provinces.length + " provinces, " +
  data.cities.length + " cities, " +
  data.districts.length + " districts\n"
)
